## Debug & Test
app.test=false
## 2 seconds execution time (120*16 ms)
app.test.loop.max.count=1200
app.exit=false
app.debug.level=3
## Render process
app.render.window.title="Test001 Demo App"
app.render.window.size=640x400
app.render.buffer.size=320x200
app.render.buffer.strategy=3
app.render.fps=60
## Physic Engine
app.physic.world.play.area.size=1080x800
app.physic.world.gravity=(0,-0.981)
## Scenes management
app.scene.list=play:com.snapgames.demo.scenes.PlayScene,
app.scene.default=play
